site_name: Graphene CRUDDALS

theme: readthedocs

repo_url: https://github.com/juanjcardona13/graphene-cruddals

edit_uri: tree/main/docs/content

plugins:
  - search
  - mkdocstrings

extra:
  edit_on_github: true

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
      separator: "-"


nav:
  - Home: index.md
