name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Set Python for pre-commit
      run: echo "PRE_COMMIT_HOME=$(python3.10 -m site --user-base)/pre-commit" >> $GITHUB_ENV
    - name: Run pre-commit 💅
      run: |
        pre-commit clean
        pre-commit autoupdate
        tox
      env:
        TOXENV: pre-commit
