name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        django: ["3.2", "4.2", "5.0"]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          - django: "3.2"
            python-version: "3.11"
          - django: "3.2"
            python-version: "3.12"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Codecov
      uses: codecov/codecov-action@v4.4.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
